POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHh5ei5jb20iLCJleHAiOjE3NDg5NDc2OTUsInVzZXJJZCI6MX0.3EfMED2xJns-yGXYuP1npovrmu4vWWIC2Lx4AgHb1G0

{
    "name":"Robin",
    "description":"great",
    "location": "India",
    "dateTime": "2000-03-30T00:00:00Z"
}