name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go with the latest version (replace with your desired Go version)
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Replace with the latest stable version

      # Clear Go module cache
      - name: Clear Go module cache
        run: go clean -modcache

      # Tidy and download modules
      - name: Tidy and download modules
        run: |
          go mod tidy
          go mod download

      # Build the project
      - name: Build
        run: go build -v ./...

      # Run tests (optional)
      - name: Run Tests
        run: go test -v ./...
